export const LAYOUT = {
  SIDEBAR_WIDTH: 300,
  MOBILE_MENU_SIZE: 60,
};

export const KANJI_CARD = {
  WIDTH: 100,
  GAP_X: 10,
  GAP_Y: 30,
  BASE_HEIGHT: 138,
  INPUT_HEIGHT: 32,
  DEFAULT_ITEMS_PER_PAGE: 100,
};
